name: Update Melon Playlist

on: 
  schedule:
      # Runs at 5:05 UTC every day
      - cron: '5 5 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: |
          git clone https://github.com/JohnHKoh/MelonYTMPlaylist.git
      - name: Install dependencies
        run: |
          pip install ytmusicapi
          pip install pyquery
      - name: Run script
        env:
          RAW_HEADERS: ${{ secrets.RAW_HEADERS }}
          CONFIG_JSON: ${{ secrest.CONFIG_JSON }}
        run: |
          cd ./MelonYTMPlaylist
          echo "$RAW_HEADERS" >> raw_headers.txt
          echo "$CONFIG_JSON" >> config.json
          cd src
          python setup.py
          python daily.py