name: Top100 Melon Playlist

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: MelonYTMPlaylist/src/song_cache.json
          key: song-cache-${{ runner.os }}
          restore-keys: |
            song-cache-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt

      - name: Run script
        env:
          RAW_HEADERS: ${{ secrets.RAW_HEADERS }}
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
        run: |
          echo "$RAW_HEADERS" > raw_headers.txt
          echo "$CONFIG_JSON" > config.json
          cd src
          python setup.py
          python top100.py

      - name: Save cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: MelonYTMPlaylist/src/song_cache.json
          key: song-cache-${{ runner.os }}-${{ github.run_id }}
