name: Weekly Melon Playlist

on:
  schedule:
    # Runs at 5:05 UTC every Monday
    - cron: "5 5 * * MON"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: |
          git clone https://github.com/JohnHKoh/MelonYTMPlaylist.git
          cd MelonYTMPlaylist
      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
      - name: Run script
        env:
          RAW_HEADERS: ${{ secrets.RAW_HEADERS }}
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
        run: |
          echo "$RAW_HEADERS" >> raw_headers.txt
          echo "$CONFIG_JSON" >> config.json
          cd src
          python setup.py
          python weekly.py
