name: Update Melon Playlist

on: 
  schedule:
      # Runs at 5:05 UTC every day
      - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: |
          git clone https://github.com/JohnHKoh/MelonYTMPlaylist.git
      - name: Install dependencies
        run: |
          pip install ytmusicapi
          pip install pyquery
      - name: Run script
        env:
          BRAND_ACCOUNT: ${{ secrets.BRAND_ACCOUNT }}
          RAW_HEADERS: ${{ secrets.RAW_HEADERS }}
          PLAYLIST_ID: ${{ secrets.PLAYLIST_ID }}
        run: |
          cd ./MelonYTMPlaylist
          echo "$RAW_HEADERS" >> raw_headers.txt
          echo "{\"brand_account\": \"$BRAND_ACCOUNT\",\"playlist_id\": \"$PLAYLIST_ID\"}" >> config.json
          python src/setup.py
          python src/daily.py